## NumPy Arrays Essential

In this notebook, we'll cover the following fundamental concepts of NumPy.

In [1]:
import numpy as np

### Creating NumPy arrays

In [2]:
# creating an array using Python lists

a_list = [3,4,5]
np.array(a_list)

array([3, 4, 5])

In [3]:
# creating array of linearly-spaced elements
# starting with 0, ending at 30 stepping by 3

np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
# creating an array by dividing a range into a number of parts
# starting with 0 and ending at 10 divided into 5 elements

np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
# creating a 2D array with normally distributed random values
# mean at 0 and standard deviation 1

np.random.normal(0,1,(3,3))

array([[-0.06964919, -3.02887372, -1.01702468],
       [ 0.72734282,  0.53916189, -0.17533194],
       [-1.2041271 ,  1.20514296,  1.62190962]])

### Useful array attributes

In [6]:
## set a seed value to generate same random values on every run
np.random.seed(0)

# create 3 arrays(1D, 2D & 3D)
arr1 = np.random.randint(10, size=6)
arr2 = np.random.randint(10, size=(3,4))
arr3 = np.random.randint(10, size =(3,4,5))

In [7]:
## printing the dimension, shape, size and bytes of an array
print("Arr3 ndim: ", arr3.ndim)
print("Arr3 shape: ", arr3.shape)
print("Arr3 size: ", arr3.size)
print("Arr3 bytes: ", arr3.nbytes, "bytes")

Arr3 ndim:  3
Arr3 shape:  (3, 4, 5)
Arr3 size:  60
Arr3 bytes:  480 bytes


### How to access elements of an array (i.e. indexing and slicing)?

In [8]:
print("1D Array: \n", arr1)

print("First element: \n", arr1[0])

print("Last element: \n", arr1[-1])

print("First 3 elements of the array: \n", arr1[:3])

print("Elements after the 4th index \n", arr1[4:])

print("Subarray from 3rd index to 7th: \n", arr1[3:8])

print("Alternate elements: \n", arr1[::2])

print("Reversed array: \n", arr1[::-1])

1D Array: 
 [5 0 3 3 7 9]
First element: 
 5
Last element: 
 9
First 3 elements of the array: 
 [5 0 3]
Elements after the 4th index 
 [7 9]
Subarray from 3rd index to 7th: 
 [3 7 9]
Alternate elements: 
 [5 3 7]
Reversed array: 
 [9 7 3 3 0 5]


In [11]:
print("2D Array: \n", arr2)

print("2nd Element of the 3rd row: \n", arr2[2, 1])

print("Slicing the array to get 2nd and 3rd rows: \n", arr2[1:,:])

print("Alternate columns: \n", arr2[:,::2])

2D Array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
2nd Element of the 3rd row: 
 6
Slicing the array to get 2nd and 3rd rows: 
 [[7 6 8 8]
 [1 6 7 7]]
Alternate columns: 
 [[3 2]
 [7 8]
 [1 7]]
