## NumPy Arrays Essential

In this notebook, we'll cover the following fundamental concepts of NumPy:

1. How to create NumPy arrays.
2. How to find out the array's dimension, shape, size and byte size.
3. How to access elements using indexing and slicing.
4. How to create copies of subarrays.
5. How to reshape arrays

Import NumPy if you don't have it installed in your environment

In [1]:
!pip install numpy

You should consider upgrading via the 'pip install --upgrade pip' command.


I'd recommend NumPy version 1.8 or later.

In [3]:
import numpy as np

numpy.__version__

'1.19.0'

### NumPy arrays

NumPy has the ndarray object that not only provides efficient storage of array-based data but also offers useful and efficient operations on the data.

Looking at a few methods of creating arrays using NumPy.

In [5]:
# creating an array using Python lists
a_list = [3.0, 4 ,5]
np.array(a_list)

array([3., 4., 5.])

In [4]:
# creating array of linearly-spaced elements
# starting with 0, ending at 30 stepping by 3
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
# creating an array by dividing a range into a number of parts
# starting with 0 and ending at 10 divided into 5 elements
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
# creating a 2D array with normally distributed random values
# mean at 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.21151317,  0.73759818, -0.47658339],
       [ 0.82534251,  0.26411792,  0.05823502],
       [-0.44395852,  1.64524576,  0.69205214]])

### Useful array attributes

In [16]:
## set a seed value to generate same random values on every run
np.random.seed(0)

# create 3 arrays(1D, 2D & 3D)
arr1 = np.random.randint(10, size=6)
arr2 = np.random.randint(10, size=(3,4))
arr3 = np.random.randint(10, size=(3, 4, 5))

In [20]:
## printing the dimension, shape, size and bytes of an array
print("Arr3 ndim: ", arr3.ndim)
print("Arr3 shape: ", arr3.shape)
print("Arr3 size: ", arr3.size)
print("Arr3 bytes: ", arr3.nbytes, "bytes")

Arr3 ndim:  3
Arr3 shape:  (3, 4, 5)
Arr3 size:  60
Arr3 bytes:  480 bytes


### How to access elements of an array (i.e. indexing and slicing)?

In [23]:
##printing the 1D array
print(arr1)

## printing the first element
print(arr1[0])

## printing the last element, indexing from the end of the array
print(arr1[-1])

##printing a slice of elements syntax: arr[start : stop : step]
##printing the first 3 elements of the array
print(arr1[:3])

##printing elements after the 4th index
print(arr1[4:])

##printing middle subarray
print(arr1[3:8])

##printing every other element
print(arr1[::2])

##printing the arraye reversed
print(arr1[::-1])

[5 0 3 3 7 9]
5
9
[5 0 3]
[7 9]
[3 7 9]
[5 3 7]
[9 7 3 3 0 5]


In [27]:
##print the 2D array
print(arr2)

## print the 2nd element of third row
print(arr2[2,1])


##print the 2nd and 3rd rows of the array
print(arr2[1:, :])


##print all rows every other column
print(arr2[:3, ::2])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
6
[[7 6 8 8]
 [1 6 7 7]]
[[3 2]
 [7 8]
 [1 7]]


### Creating copies of an Array/Subarray

Python slicing creates copies but NumPy creates views thus it is always useful to explicitly create copies of arrays using the `copy()` method

In [30]:
##We can use the copy() method to make copies of an arrays and subarrays
print(arr2)

arr2_sub_copy = arr2[:3, :3].copy()

print(arr2_sub_copy)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]
 [1 6 7]]


### Reshaping Arrays

In [34]:
# printing arr2 for reference
print(arr2)

# reshaping the 2D array arr2 from (3,4) to (4,3) using the reshape() method
arr2_reshaped = arr2.reshape(4,3)

print(arr2_reshaped)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]]


In [38]:
# converting a 1D array into a 2D array
x = np.array([1,2,3])
print(x)

# creating a row vector using reshape()
print(x.reshape((1,3)))

# creating a row vector using newaxis
print(x[np.newaxis, :])

[1 2 3]
[[1 2 3]]
[[1 2 3]]


In [40]:
# creating a column vector using reshape()
print(x.reshape((3,1)))

# creating a column vector using newaxis
print(x[:, np.newaxis])

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
