## Broadcasting

This notebooks explains broadcasting, a widely used operation in data science. 
We'll cover:
1. How to vectorize arrays using NumPy. 
2. What are the rules of broadcasting
3. How does each rule look in practice(examples of broadcasting)

In [1]:
import numpy as np

### Broadcasting 

A functionality that states a set of rules to apply binary universal functions(addition, subtraction, multiplication, etc.) on arrays of varied sizes.

In [2]:
##defining 2 arrays and adding them as vectors
a = np.array([3,5,7])
b = np.array([2,4,6])

a + b

array([ 5,  9, 13])

In [3]:
a + 10

array([13, 15, 17])

In [4]:
##creating an array of 1s.

ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
##adding a vector to a 2D array; broadcasting one value to match the shape of the other
ones + a

array([[4., 6., 8.],
       [4., 6., 8.],
       [4., 6., 8.]])

In [19]:
##adding arrays of different shape; stretching both a & b to match a common shape

print(np.arange(3))
print(np.ones((3,1)))
print(np.ones((3,1)) + np.arange(3))

[0 1 2]
[[1.]
 [1.]
 [1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


### Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [21]:
##example of rule 1
a = np.ones((2, 3))
b = np.arange(3)
a + b

array([[1., 2., 3.],
       [1., 2., 3.]])

In [23]:
##example of rule 2
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [29]:
##example of rule 3
a = np.ones((3, 2))
b = np.arange(3)
a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 