## Comparison, Masking and Boolean Logic

This notebooks explains how we can use NumPy to manipulate array values based on a criterion, we'll talk about the following:

1. How to use comparison operators as element-wise universal functions.
2. How to use boolean arrays with composite conditions.
3. How to use boolean arrays as masks to extract the required values.

In [2]:
import numpy as np

In [3]:
##defining an array
arr = np.array([10,20,30,40,50])

arr >= 20

array([False,  True,  True,  True,  True])

In [4]:
arr == 30

array([False, False,  True, False, False])

In [5]:
##equivalent ufunc for the comparison operator
np.greater(arr, 30)

array([False, False, False,  True,  True])

### Boolean Arrays

In [6]:
##creating a 2D array of random integers with values < 10
arr = np.random.randint(10, size=(3,4))
arr

array([[0, 3, 7, 4],
       [4, 7, 3, 2],
       [2, 2, 0, 2]])

In [7]:
##counting number of values that are greater than 5 using np.sum()
np.sum(arr > 5)

2

In [8]:
##counting number of values that are greater than 5 in each row
np.sum(arr > 5, axis=1)

array([1, 1, 0])

In [9]:
##checking if any or all value are above or below a threshold
np.any(arr > 5)

True

In [10]:
##check if all values are > 5
np.all(arr > 5)

False

## Boolean Operators to handle multiple conditions

In [11]:
##math test scores of students in a class
test_scores = np.random.randint(100, size=(30))
test_scores


array([67, 32, 64, 69, 54, 16, 74, 99, 17, 32, 30, 89, 25, 21,  5,  2, 67,
       45, 82, 63, 50, 26, 60, 88, 49, 81, 33, 70, 59, 98])

In [12]:
##number of students who scored more than 50 but less than 75

np.sum((test_scores > 50) & (test_scores < 75))

10

In [13]:
##extracting all the indices which meet the condition
np.where((test_scores > 50) & (test_scores < 75))

(array([ 0,  2,  3,  4,  6, 16, 19, 22, 27, 28]),)

## Masking

Using Boolean arrays as masks

In [18]:
##Extracting all the elements(values) that adhere to the mask
# mask = test_scores > 75
mask = (test_scores > 50) & (test_scores < 75)

In [19]:
test_scores[mask]

array([67, 64, 69, 54, 74, 67, 63, 60, 70, 59])